language: bash
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y curl discount unzip
- wget -O /tmp/gmirror-0.2.2.tar.gz https://github.com/sinkcup/gmirror/archive/0.2.2.tar.gz
- tar -zxvf /tmp/gmirror-0.2.2.tar.gz -C /tmp/
- cp /tmp/gmirror-0.2.2/*.sh /tmp/gmirror-0.2.2/tpl.html ./
install:
- bash ./download.sh
script:
- test $TRAVIS_PULL_REQUEST == "false" && echo "travis-ci don't support qiniu, so deploy manually" || exit 0
- bash ./before_upload.sh
- export PATH=$PATH:$PWD/qiniu/
- bash ./upload.sh
