language: bash
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y discount
install:
- bash ./download.sh
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && echo "travis-ci don't support qiniu, so deploy manually" || exit 0
- wget -O /tmp/qiniu-devtools-linux_amd64-current.tar.gz http://devtools.qiniu.io/qiniu-devtools-linux_amd64-current.tar.gz
- mkdir qiniu
- tar -zxvf /tmp/qiniu-devtools-linux_amd64-current.tar.gz -C ./qiniu/
- export PATH=$PATH:$PWD/qiniu/
- rm -f dl/*.tmp dl/*.html dl/*.md dl/*.dl
- sed -e "s|{src}|$PWD/dl|g" -e "s|{access_key}|$qiniu_access_key|g" -e "s|{secret_key}|$qiniu_secret_key|g" qiniu.json > qiniu.json
- qrsync-v2 qiniu.json
- bash ./index.sh -u $qiniu_user -p $qiniu_passwd
