language: bash
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y curl discount unzip
- wget -O /tmp/gmirror.tar.gz https://github.com/sinkcup/gmirror/archive/0.1.0.tar.gz
- mkdir -p /tmp/gmirror
- tar -zxvf /tmp/gmirror.tar.gz -C /tmp/gmirror
- cp /tmp/gmirror/*.sh /tmp/gmirror/tpl.html ./
install:
- bash ./download.sh
script:
- test $TRAVIS_PULL_REQUEST == "false" && echo "travis-ci don't support qiniu, so deploy manually" || exit 0
- bash ./before_upload.sh
- export PATH=$PATH:$PWD/qiniu/
- bash ./upload.sh
